### ISSUE TITLE
Sign-In Page Selection Issue

### ISSUE THREAD

**Issue by andypotanin** [UsabilityDynamics/wp-google-identity#2]
![image](https://cloud.githubusercontent.com/assets/1255935/8244345/a9bbd3b4-15ed-11e5-9e33-a5f25e4ea34b.png)

![image](https://cloud.githubusercontent.com/assets/1255935/8244353/b57bcd6c-15ed-11e5-81be-2c8574ec79e4.png)

![image](https://cloud.githubusercontent.com/assets/1255935/8244367/d4faf29e-15ed-11e5-8222-0fa975185ce8.png)

**Comment by andypotanin** [comment]
Ah, figured it out.  Should clarify in help message though.

![image](https://cloud.githubusercontent.com/assets/1255935/8244395/2f513cbc-15ee-11e5-812a-73fe064b0498.png)

**Comment by pemaxim** [comment]
It's already clarified here:
http://screencast.com/t/F9l4pj19pl
